sudo: false

language: python

python:
  - "2.7"

install: "pip install -r requirements.txt"


# Command to run tests
script:
#  - coverage run tests.py
#  - python my_tests.py

# after_success:
#   - codecov

branches:
  only:
    - master

notifications:
  email: true
	recipients:
     	- jizzard@redventures.com
  on_success: change
  on_failure: always
